[package]
name = "tcp-relay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.144"
serde_json = "1.0.85"
websocket = "0.26.5"
chat_server = { path = "../chat_server" }
